In [11]:
# pip install numpy
import numpy as np

array1 = np.array(
    [
    [ [1, 2, 3, 4, 5], [2,4,6,8,10]],
    [ [6, 7, 8, 9, 10], [12,14,16,18,20]]
    ]
    )

print(array1.ndim)
print(array1.shape)


3
(2, 2, 5)


In [ ]:
import numpy as np

array1 = np.array([
    [1, 2, 3, 4, 5], 
    [2, 4, 6, 8, 10]
    ])

#shape 
print(array1.ndim)
print(array1.shape)




2
(2, 5)


In [ ]:
import numpy as np

array2 = np.array(
    [
    [ [1, 2, 3, 4, 5], [2,4,6,8,10]],
    [ [6, 7, 8, 9, 10], [12,14,16,18,20]]
    ]
    )

print(array2.ndim)
print(array2.shape)
print(array2[1, 1, 1])  # Accessing the first element of the first sub-array


3
(2, 2, 5)
14


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr[2:10])
print(arr[2:])
print(arr[:5])
# sliceing 

[ 3  4  5  6  7  8  9 10]
[ 3  4  5  6  7  8  9 10]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array(
    [[[1, 2, 3, 4, 5],
      [2, 4, 6, 8, 10],
      [6, 7, 8, 9, 10]]]
    )

print(arr.ndim)
print(arr.shape)
print(arr[0,1,2:])
#8,9,10


3
(1, 3, 5)
[ 6  8 10]


In [ ]:
import numpy as np
array1 = np.array(
    [[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
     [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
     [6, 7, 8, 9, 10, 11, 12, 13, 14, 15]]]
    )
print(array1.ndim)  # Accessing elements from index 2 to 7 in the second row



3
